[versions]
agp = "8.6.1"
kotlin = "2.1.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.0"
lifecycleKtx = "2.8.7"
root_version = "2.7.0"
navigationFrgKtx = "2.8.7"
recyclerview_version = "1.4.0"
cardview_version = "1.0.0"
coil_version = "2.4.0"
calendarview_version = "2.4.0"
mpandroidchart_version = "v3.1.0"
readium_version = "2.4.0"
coroutines_version = "1.7.3"
gson_version = "2.10.1"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson_version" }
readium-shared = { module = "org.readium.kotlin-toolkit:readium-shared", version.ref = "readium_version" }
readium-streamer = { module = "org.readium.kotlin-toolkit:readium-streamer", version.ref = "readium_version" }
readium-navigator = { module = "org.readium.kotlin-toolkit:readium-navigator", version.ref = "readium_version" }
readium-opds = { module = "org.readium.kotlin-toolkit:readium-opds", version.ref = "readium_version" }
readium-lcp = { module = "org.readium.kotlin-toolkit:readium-lcp", version.ref = "readium_version" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFrgKtx"}
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart_version" }
calendarview = { module = "com.kizitonwose.calendar:view", version.ref = "calendarview_version" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFrgKtx"}
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview_version"}
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleKtx"}
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleKtx"}
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines_version"}
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "root_version"}
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "root_version"}
io-coil-kt = { module = "io.coil-kt:coil", version.ref = "coil_version"}
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "root_version" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview_version"}
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationFrgKtx" }
android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

